"""
This module provides classes for loading datasets generated by DataGenerator.
"""

import json
import os
from dataclasses import dataclass, field
from typing import Tuple
import warnings

import geopandas as gpd
import numpy as np
import shapely
from pyproj import CRS

from sarenv.utils.logging_setup import get_logger
from sarenv.utils.lost_person_behavior import get_environment_radius_by_size, get_available_sizes
from sarenv.utils.geo import get_utm_epsg
log = get_logger()

FEATURE_MASK_LAYER_PREFIX = "feature_mask:"


@dataclass
class SARDatasetItem:
    """
    A dataclass to hold the data for a single generated SAR environment size.

    Attributes:
        size (str): The name of the size (e.g., 'small', 'medium').
        center_point (tuple[float, float]): The (longitude, latitude) of the dataset's center.
        radius_km (float): The radius used to generate this dataset item.
        bounds (tuple[float, float, float, float]): The projected bounds (minx, miny, maxx, maxy) of the data.
        features (gpd.GeoDataFrame): A GeoDataFrame containing all geographic features.
        heatmap (np.ndarray): A 2D NumPy array representing the probability heatmap. Its sum reflects the probability mass within this clip.
        layers (dict[str, np.ndarray]): Optional rasters aligned to the SAR
            heatmap, currently used for persisted feature masks only.
    """

    size: str
    center_point: tuple[float, float]
    radius_km: float
    bounds: Tuple[float, float, float, float]
    features: gpd.GeoDataFrame
    heatmap: np.ndarray
    environment_climate: str
    environment_type: str
    meter_per_bin: float = 30.0
    projected_crs: str | None = None
    layers: dict[str, np.ndarray] = field(default_factory=dict)

    @property
    def radiation_map(self) -> np.ndarray | None:
        """Deprecated: radiation is no longer a heatmap-aligned SAR layer."""
        warnings.warn(
            "SARDatasetItem.radiation_map is deprecated. Load independent "
            "radiation patches through sarenv.radiation instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return None

    @property
    def feature_masks(self) -> dict[str, np.ndarray]:
        """Return aligned feature-mask arrays without copying their data."""
        return {
            layer_name.removeprefix(FEATURE_MASK_LAYER_PREFIX): layer
            for layer_name, layer in self.layers.items()
            if layer_name.startswith(FEATURE_MASK_LAYER_PREFIX)
        }


class DatasetLoader:
    """
    Load a SAR dataset according to its saved spatial contract.

    ``metadata.json`` is authoritative for current datasets. A requested size
    equal to the saved size is returned without cropping. Cropping is allowed
    only from a larger saved dataset to a smaller requested size.
    """

    def __init__(self, dataset_directory: str):
        """
        Initializes the DynamicDatasetLoader.

        Args:
            dataset_directory (str): The path to the directory containing the master dataset files.
        """
        if not os.path.isdir(dataset_directory):
            log.error(f"Dataset directory not found at: {dataset_directory}")
            raise FileNotFoundError(
                f"The specified directory does not exist: {dataset_directory}"
            )

        self.dataset_directory = dataset_directory
        self.master_features_path = os.path.join(
            self.dataset_directory, "features.geojson"
        )
        self.master_heatmap_path = os.path.join(self.dataset_directory, "heatmap.npy")
        self.metadata_path = os.path.join(self.dataset_directory, "metadata.json")
        self.master_feature_masks_path = os.path.join(
            self.dataset_directory, "feature_masks.npz"
        )

        if not os.path.exists(self.master_features_path):
            raise FileNotFoundError(
                f"Master features file not found: {self.master_features_path}"
            )
        if not os.path.exists(self.master_heatmap_path):
            raise FileNotFoundError(
                f"Master heatmap file not found: {self.master_heatmap_path}"
            )

        # Cache for lazy-loading the master data
        self._master_features_gdf = None
        self._master_features_gdf_proj = None
        self._master_probability_map = None
        self._master_layers = {}
        self._center_point = None
        self._projected_crs = None
        self._meter_per_bin = None
        self._bounds = None
        self._climate = None
        self._environment_type = None
        self._dataset_size = None
        self._dataset_radius_km = None
        self._metadata = None

    def _infer_legacy_size(self, radius_km: float) -> str:
        """Resolve an old dataset size explicitly from its saved radius."""
        matching_sizes = [
            size
            for size in get_available_sizes()
            if np.isclose(
                get_environment_radius_by_size(
                    self._environment_type, self._climate, size
                ),
                radius_km,
            )
        ]
        if len(matching_sizes) != 1:
            raise ValueError(
                "Legacy dataset metadata does not identify a unique "
                f"environment size for radius_km={radius_km}."
            )
        warnings.warn(
            "Dataset metadata has no environment_size; using the explicit "
            f"legacy radius mapping to resolve '{matching_sizes[0]}'.",
            DeprecationWarning,
            stacklevel=3,
        )
        return matching_sizes[0]

    @staticmethod
    def _metadata_value(
        metadata: dict,
        geojson_data: dict,
        metadata_key: str,
        geojson_key: str | None = None,
    ):
        """Read a current metadata value with an explicit legacy fallback."""
        if metadata_key in metadata:
            return metadata[metadata_key]
        legacy_key = geojson_key or metadata_key
        if legacy_key in geojson_data:
            return geojson_data[legacy_key]
        raise KeyError(metadata_key)

    @staticmethod
    def _validate_duplicate_metadata(
        metadata: dict,
        geojson_data: dict,
    ) -> None:
        """Reject conflicting duplicated base metadata instead of guessing."""
        key_pairs = {
            "center_point": "center_point",
            "environment_type": "environment_type",
            "climate": "climate",
            "meter_per_bin": "meter_per_bin",
            "radius_km": "radius_km",
            "environment_size": "environment_size",
            "bounds_projected": "bounds",
        }
        for metadata_key, geojson_key in key_pairs.items():
            if metadata_key not in metadata or geojson_key not in geojson_data:
                continue
            authoritative = metadata[metadata_key]
            duplicate = geojson_data[geojson_key]
            if isinstance(authoritative, (list, tuple)):
                matches = np.allclose(authoritative, duplicate, rtol=0.0, atol=1e-6)
            elif isinstance(authoritative, (int, float)):
                matches = np.isclose(authoritative, duplicate, rtol=0.0, atol=1e-9)
            else:
                matches = authoritative == duplicate
            if not matches:
                raise ValueError(
                    f"metadata.json {metadata_key!r} conflicts with "
                    f"features.geojson {geojson_key!r}."
                )

    def _load_master_data_if_needed(self):
        """Loads the master GeoJSON and probability map from disk if not already in cache."""
        if self._master_probability_map is not None:
            return

        log.info("Loading SAR dataset from disk for the first time...")
        try:
            with open(self.master_features_path, "r", encoding="utf-8") as f:
                geojson_data = json.load(f)

            metadata = {}
            if os.path.exists(self.metadata_path):
                with open(self.metadata_path, "r", encoding="utf-8") as f:
                    metadata = json.load(f)
                if not isinstance(metadata, dict):
                    raise ValueError("metadata.json must contain a JSON object.")
                self._validate_duplicate_metadata(metadata, geojson_data)
                if "environment_size" in metadata:
                    expected_contract = {
                        "schema_version": 1,
                        "dataset_type": "sarenv_base",
                        "quantity": "lost_person_probability",
                        "probability_contract": (
                            "sum_to_one_within_saved_environment"
                        ),
                        "heatmap_filename": "heatmap.npy",
                        "features_filename": "features.geojson",
                        "raster_origin": "lower",
                        "raster_axis_order": "row_y_column_x",
                    }
                    for key, expected_value in expected_contract.items():
                        if metadata.get(key) != expected_value:
                            raise ValueError(
                                f"Current SAR metadata contract {key!r} is "
                                "missing or incompatible."
                            )
            else:
                warnings.warn(
                    "metadata.json is missing; loading explicit legacy metadata "
                    "from features.geojson.",
                    DeprecationWarning,
                    stacklevel=2,
                )

            self._metadata = metadata
            self._center_point = tuple(
                float(value)
                for value in self._metadata_value(
                    metadata, geojson_data, "center_point"
                )
            )
            self._meter_per_bin = float(
                self._metadata_value(
                    metadata, geojson_data, "meter_per_bin"
                )
            )
            if not np.isfinite(self._meter_per_bin) or self._meter_per_bin <= 0:
                raise ValueError("Saved meter_per_bin must be finite and positive.")
            self._bounds = tuple(
                float(value)
                for value in self._metadata_value(
                    metadata,
                    geojson_data,
                    "bounds_projected",
                    "bounds",
                )
            )
            if len(self._bounds) != 4 or not np.isfinite(self._bounds).all():
                raise ValueError("Saved projected bounds must contain four finite values.")
            if self._bounds[2] <= self._bounds[0] or self._bounds[3] <= self._bounds[1]:
                raise ValueError("Saved projected bounds are invalid.")
            self._climate = str(
                self._metadata_value(metadata, geojson_data, "climate")
            )
            self._environment_type = str(
                self._metadata_value(
                    metadata, geojson_data, "environment_type"
                )
            )
            self._dataset_radius_km = float(
                self._metadata_value(metadata, geojson_data, "radius_km")
            )
            saved_size = metadata.get(
                "environment_size", geojson_data.get("environment_size")
            )
            self._dataset_size = (
                str(saved_size)
                if saved_size is not None
                else self._infer_legacy_size(self._dataset_radius_km)
            )
            if self._dataset_size not in get_available_sizes():
                raise ValueError(
                    f"Unsupported saved environment_size: {self._dataset_size!r}."
                )
            expected_radius_km = get_environment_radius_by_size(
                self._environment_type,
                self._climate,
                self._dataset_size,
            )
            if not np.isclose(
                self._dataset_radius_km,
                expected_radius_km,
                rtol=0.0,
                atol=1e-9,
            ):
                raise ValueError(
                    "Saved radius_km is inconsistent with environment_size, "
                    "environment_type, and climate."
                )
            projected_crs = metadata.get("projected_crs")
            self._projected_crs = (
                str(projected_crs)
                if projected_crs is not None
                else get_utm_epsg(
                    self._center_point[0], self._center_point[1]
                )
            )
            if not CRS.from_user_input(self._projected_crs).is_projected:
                raise ValueError("Saved SAR projected_crs must be a projected CRS.")
            log.info(
                "Loaded authoritative dataset metadata: size=%s, center=%s, "
                "resolution=%s m/bin, CRS=%s",
                self._dataset_size,
                self._center_point,
                self._meter_per_bin,
                self._projected_crs,
            )

            # --- Load Main Data ---
            feature_values = geojson_data.get("features")
            if not isinstance(feature_values, list):
                raise ValueError("features.geojson 'features' must be a list.")
            if feature_values:
                self._master_features_gdf = gpd.GeoDataFrame.from_features(
                    feature_values, crs="EPSG:4326"
                )
            else:
                self._master_features_gdf = gpd.GeoDataFrame(
                    {"geometry": []}, geometry="geometry", crs="EPSG:4326"
                )
            self._master_features_gdf_proj = self._master_features_gdf.to_crs(
                self._projected_crs
            )
            self._master_probability_map = np.load(
                self.master_heatmap_path, allow_pickle=False
            )
            if self._master_probability_map.ndim != 2:
                raise ValueError("heatmap.npy must contain one 2D array.")
            if not np.isfinite(self._master_probability_map).all() or (
                self._master_probability_map < 0
            ).any():
                raise ValueError(
                    "heatmap.npy must contain finite, non-negative probabilities."
                )
            saved_shape = metadata.get("raster_shape")
            if saved_shape is not None and tuple(saved_shape) != (
                self._master_probability_map.shape
            ):
                raise ValueError(
                    "heatmap.npy shape does not match metadata.json raster_shape."
                )
            expected_width_m = (
                self._master_probability_map.shape[1] * self._meter_per_bin
            )
            expected_height_m = (
                self._master_probability_map.shape[0] * self._meter_per_bin
            )
            saved_width_m = self._bounds[2] - self._bounds[0]
            saved_height_m = self._bounds[3] - self._bounds[1]
            if not np.isclose(
                saved_width_m, expected_width_m, rtol=0.0, atol=1e-6
            ) or not np.isclose(
                saved_height_m, expected_height_m, rtol=0.0, atol=1e-6
            ):
                raise ValueError(
                    "Saved bounds, meter_per_bin, and heatmap shape describe "
                    "different raster extents."
                )
            if "environment_size" in metadata and not np.isclose(
                self._master_probability_map.sum(), 1.0, atol=1e-6
            ):
                raise ValueError(
                    "A current direct-size SAR dataset must contain a heatmap "
                    "whose probability sum is 1.0."
                )
            log.info(
                "Loaded probability map with shape %s and sum %.12f",
                self._master_probability_map.shape,
                self._master_probability_map.sum(),
            )

            if os.path.exists(self.master_feature_masks_path):
                with np.load(
                    self.master_feature_masks_path, allow_pickle=False
                ) as feature_masks:
                    for feature_name in feature_masks.files:
                        layer_name = (
                            f"{FEATURE_MASK_LAYER_PREFIX}{feature_name}"
                        )
                        feature_mask = feature_masks[feature_name]
                        self._validate_optional_layer(
                            layer_name, feature_mask, require_finite=False
                        )
                        self._master_layers[layer_name] = feature_mask
                log.info(
                    "Loaded optional master feature masks: "
                    f"{len(self._master_layers)}"
                )

        except KeyError as e:
            log.error(
                f"Could not find required key '{e}' in {self.master_features_path}. The file might be corrupt or incomplete."
            )
            raise
        except Exception as e:
            log.error(
                f"An error occurred while loading the master dataset: {e}",
                exc_info=True,
            )
            raise

    def _validate_optional_layer(
        self,
        layer_name: str,
        layer: np.ndarray,
        *,
        require_finite: bool,
    ) -> None:
        """Validate an optional master layer against the required heatmap grid."""
        if layer.shape != self._master_probability_map.shape:
            raise ValueError(
                f"Optional layer '{layer_name}' shape {layer.shape} does not "
                "match master heatmap shape "
                f"{self._master_probability_map.shape}."
            )
        if require_finite and not np.isfinite(layer).all():
            raise ValueError(
                f"Optional layer '{layer_name}' contains NaN or infinite values."
            )


    def _world_to_image_for_master(
        self, x_world: np.ndarray, y_world: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        """Converts world coordinates (projected) to pixel coordinates of the master heatmap."""
        master_minx, master_miny, _, _ = self._bounds
        x_img = (x_world - master_minx) / self._meter_per_bin
        y_img = (y_world - master_miny) / self._meter_per_bin
        return x_img.astype(int), y_img.astype(int)

    @property
    def dataset_size(self) -> str:
        """Return the authoritative saved environment size."""
        self._load_master_data_if_needed()
        return self._dataset_size

    def load_environment(self, size: str | None = None) -> SARDatasetItem | None:
        """
        Loads the master data and clips it to a specified size. The resulting
        heatmap is a crop of the master probability map, and its sum will reflect
        its portion of the total probability.

        Args:
            size (str): The name of the size to load (e.g., 'medium').

        Returns:
            SARDatasetItem | None: A dataclass instance containing the clipped/cropped data.
        """
        self._load_master_data_if_needed()
        requested_size = self._dataset_size if size is None else size
        if requested_size not in get_available_sizes():
            raise ValueError(f"Unsupported requested environment size: {requested_size!r}.")
        saved_index = get_available_sizes().index(self._dataset_size)
        requested_index = get_available_sizes().index(requested_size)
        if requested_index > saved_index:
            raise ValueError(
                f"Cannot load '{requested_size}' from a physically smaller "
                f"'{self._dataset_size}' dataset."
            )
        log.info(
            "Loading environment size '%s' from saved '%s' dataset.",
            requested_size,
            self._dataset_size,
        )

        if self._master_probability_map is None:
            log.error(
                "Cannot process size request because the master probability map failed to load."
            )
            return None

        radius_km = get_environment_radius_by_size(
            self._environment_type, self._climate, requested_size
        )

        if requested_size == self._dataset_size:
            log.info(
                "Requested size equals saved size; returning stored arrays "
                "without cropping or renormalisation."
            )
            return SARDatasetItem(
                size=requested_size,
                center_point=self._center_point,
                radius_km=self._dataset_radius_km,
                bounds=self._bounds,
                features=self._master_features_gdf_proj,
                heatmap=self._master_probability_map,
                environment_climate=self._climate,
                environment_type=self._environment_type,
                meter_per_bin=self._meter_per_bin,
                projected_crs=self._projected_crs,
                layers=dict(self._master_layers),
            )

        # Create clipping geometry for features
        clipping_point_wgs84 = gpd.GeoDataFrame(
            geometry=[shapely.Point(self._center_point)], crs="EPSG:4326"
        )
        clipping_point_proj = clipping_point_wgs84.to_crs(self._projected_crs)
        clipping_circle_proj = clipping_point_proj.buffer(radius_km * 1000).iloc[0]
        clipped_bounds = clipping_circle_proj.bounds

        clipped_features_proj = gpd.clip(
            self._master_features_gdf_proj, clipping_circle_proj
        )
        log.info(
            f"Clipped features to {len(clipped_features_proj)} items for size '{requested_size}'."
        )

        # Get pixel boundaries for cropping the heatmap
        min_x_w, min_y_w, max_x_w, max_y_w = clipped_bounds
        img_min_x, img_min_y = self._world_to_image_for_master(
            np.array([min_x_w]), np.array([min_y_w])
        )
        img_max_x, img_max_y = self._world_to_image_for_master(
            np.array([max_x_w]), np.array([max_y_w])
        )

        h, w = self._master_probability_map.shape
        img_min_y, img_max_y = np.clip([img_min_y[0], img_max_y[0]], 0, h)
        img_min_x, img_max_x = np.clip([img_min_x[0], img_max_x[0]], 0, w)

        # Crop the master probability map
        cropped_map = self._master_probability_map[
            img_min_y:img_max_y, img_min_x:img_max_x
        ]

        # Create a circular mask for the cropped area to ensure it's not a square
        yy, xx = np.mgrid[img_min_y:img_max_y, img_min_x:img_max_x]
        center_x_master_px = (
            clipping_point_proj.geometry.x.values[0] - self._bounds[0]
        ) / self._meter_per_bin
        center_y_master_px = (
            clipping_point_proj.geometry.y.values[0] - self._bounds[1]
        ) / self._meter_per_bin
        radius_px = (radius_km * 1000) / self._meter_per_bin
        mask = (
            (xx - center_x_master_px) ** 2 + (yy - center_y_master_px) ** 2
        ) <= radius_px**2

        # Apply mask. The resulting map is NOT re-normalized.
        # Its sum reflects its portion of the total probability.
        final_heatmap = np.where(mask, cropped_map, 0)
        log.info(
            f"Final heatmap for size '{requested_size}' has a probability sum of {np.sum(final_heatmap):.4f}"
        )

        final_layers = {}
        for layer_name, master_layer in self._master_layers.items():
            cropped_layer = master_layer[
                img_min_y:img_max_y, img_min_x:img_max_x
            ]
            if cropped_layer.shape != cropped_map.shape:
                raise ValueError(
                    f"Cropped optional layer '{layer_name}' shape "
                    f"{cropped_layer.shape} does not match cropped heatmap shape "
                    f"{cropped_map.shape}."
                )
            final_layers[layer_name] = np.where(mask, cropped_layer, 0)

        return SARDatasetItem(
            size=requested_size,
            center_point=self._center_point,
            radius_km=radius_km,
            bounds=clipped_bounds,
            features=clipped_features_proj,
            heatmap=final_heatmap,
            environment_climate=self._climate,
            environment_type=self._environment_type,
            meter_per_bin=self._meter_per_bin,
            projected_crs=self._projected_crs,
            layers=final_layers,
        )

    def load_all(self) -> dict[str, SARDatasetItem]:
        """
        Loads and processes data for all available sizes.

        Returns:
            dict[str, SARDatasetItem]: A dictionary where keys are size names
                                       and values are the corresponding SARDatasetItem objects.
        """
        self._load_master_data_if_needed()
        log.info("Loading all sizes supported by the saved dataset.")
        all_data = {}
        maximum_index = get_available_sizes().index(self._dataset_size)
        for size in get_available_sizes()[: maximum_index + 1]:
            item = self.load_environment(size)
            if item:
                all_data[size] = item
        return all_data
